const indicatorMeta = [
  {
    key: "1st_anc_visits",
    displayName: "1st ANC Visits",
    function: "single",
    numerator: { dataElementId: "Q9nSogNmKPt", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "vitamin_a1",
    displayName: "1st doses of vitamin A to U5",
    function: "single",
    numerator: { dataElementId: "vI52cxgsBNv", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
  },
  {
    key: "vitamin_a2",
    displayName: "2nd doses of vitamin A to U5",
    function: "single",
    numerator: { dataElementId: "A2ZOozUNmDz", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
  },
  {
    key: "4th_anc_visits",
    displayName: "4th ANC Visits",
    function: "single",
    numerator: { dataElementId: "RnLOFSYaAhp", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "abortions_other",
    displayName: "Abortions not related to GBV",
    function: "single",
    numerator: { dataElementId: "FlRxDBHWGid", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "abortions_gbv",
    displayName: "Abortions related to GBV",
    function: "single",
    numerator: { dataElementId: "TvqHbq8AKc7", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "anc_initiated_hiv",
    displayName: "ANC initiated on ART",
    function: "single",
    numerator: { dataElementId: "L4pwIgSDdG6", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "anc_tested_hiv",
    displayName: "ANC tested HIV",
    function: "single",
    numerator: { dataElementId: "uALBQG7TFhq", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "anc_tested_hiv_positive",
    displayName: "ANC tested HIV positive",
    function: "single",
    numerator: { dataElementId: "uzlQdD84jNj", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "bcg",
    displayName: "BCG doses to U1",
    function: "single",
    numerator: { dataElementId: "MxAg9De4cra", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "births",
    displayName: "Deliveries in unit",
    function: "single",
    numerator: { dataElementId: "idXOxt69W0e", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "births_fresh_stillbirth",
    displayName: "Deliveries in unit - fresh stillbirth",
    function: "single",
    numerator: { dataElementId: "T8W0wbzErSF", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "births_live",
    displayName: "Deliveries in unit - live",
    function: "single",
    numerator: { dataElementId: "fEz9wGsA6YU", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "births_macerated_stillbirth",
    displayName: "Deliveries in unit - macerated stillbirth",
    function: "single",
    numerator: { dataElementId: "ULL9lX3DO7V", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "dpt1",
    displayName: "DPT1 doses to U1",
    function: "single",
    numerator: { dataElementId: "Ys31ug5E3f1", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },

  {
    key: "dpt3",
    displayName: "DPT3 doses to U1",
    function: "single",
    numerator: { dataElementId: "ujs4ipzA4tb", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },

  {
    key: "hiv_positive_linked",
    displayName: "HIV positive linked to care",
    function: "single",
    numerator: { dataElementId: "VmVKCCYeHiF", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "hei_given_arv",
    displayName: "HIV-exposed infants receiving ARV",
    function: "single",
    numerator: { dataElementId: "OUGMxrtXxri", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "hiv_positive_mother_before_anc",
    displayName: "HIV-positive mothers aware of their status before ANC1",
    function: "single",
    numerator: { dataElementId: "b78oMBcC5R8", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "hpv1",
    displayName: "HPV1 doses to girls",
    function: "single",
    numerator: { dataElementId: "Gtk7tbHfVfj", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },

  {
    key: "hpv2",
    displayName: "HPV2 doses to girls",
    function: "single",
    numerator: { dataElementId: "zcT0YplhdAB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "injuries_gbv",
    displayName: "Injuries related to GBV",
    function: "single",
    numerator: { dataElementId: "bRYoCXTmJCB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "ipd_attendance",
    displayName: "IPD attendance",
    function: "single",
    numerator: { dataElementId: "UwnR5kr982Y", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "GENERAL",
    reportingFrequency: "monthly",
  },
  {
    key: "malaria_cases",
    displayName: "Malaria cases",
    function: "single",
    numerator: { dataElementId: "fUflbWWhouR", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MAL",
    reportingFrequency: "monthly",
  },
  {
    key: "malaria_deaths",
    displayName: "Malaria deaths",
    function: "single",
    numerator: { dataElementId: "IoZCByEDSnX", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MAL",
    reportingFrequency: "monthly",
  },
  {
    key: "mat_initiated_hiv",
    displayName: "Mat initiated on ART",
    function: "single",
    numerator: { dataElementId: "KDoEmOjpYnL", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "maternal_deaths",
    displayName: "Maternal deaths",
    function: "single",
    numerator: { dataElementId: "F8Iz6QcexWB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "maternity_admissions",
    displayName: "Maternity Admissions",
    function: "single",
    numerator: { dataElementId: "JY0M7eC2N42", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "contraceptives_male_condom",
    displayName: "Men using male condoms",
    function: "single",
    numerator: { dataElementId: "bkCFVYMFMed", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },

  {
    key: "breastfed_1st_hour",
    displayName: "Mothers breastfeeding after delivery",
    function: "single",
    numerator: { dataElementId: "XXZZbU4B2N3", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "mr1",
    displayName: "MR1 doses to U1",
    function: "single",
    numerator: { dataElementId: "WAjgHQVxVVm", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "newborn_deaths",
    displayName: "Newborn deaths",
    function: "single",
    numerator: { dataElementId: "hrTskGHP0Av", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "pcv1",
    displayName: "PCV1 doses to U1",
    function: "single",
    numerator: { dataElementId: "NbG01i1Md55", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "pcv3",
    displayName: "PCV3 doses to U1",
    function: "single",
    numerator: { dataElementId: "QHawVF72X6E", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "pnc_initiated_hiv",
    displayName: "PNC initiated on ART",
    function: "single",
    numerator: { dataElementId: "kGC9MVJppnk", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "pnc_tested_hiv",
    displayName: "PNC tested HIV",
    function: "single",
    numerator: { dataElementId: "L0kzvUuDu0M", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "pnc_tested_hiv_positive",
    displayName: "PNC tested HIV positive",
    function: "single",
    numerator: { dataElementId: "eerKMtKyYZt", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "postnatal_visits",
    displayName: "Postnatal Visits",
    function: "single",
    numerator: { dataElementId: "LJ8MLXHctGs", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
  },
  {
    key: "sti_other",
    displayName: "STI cases not related to SGBV",
    function: "single",
    numerator: { dataElementId: "KaqDbaq0Yce", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "sti_gbv",
    displayName: "STI cases related to SGBV",
    function: "single",
    numerator: { dataElementId: "Cw3RNymXWjr", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },

  {
    key: "tb_cases_registered",
    displayName: "TB cases registered in treatment unit",
    function: "single",
    numerator: { dataElementId: "vSaFiVhebVQ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "td1__pregnant",
    displayName: "TD1 doses (pregnant)",
    function: "single",
    numerator: { dataElementId: "oj4ttY118Fg", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "td2__pregnant",
    displayName: "TD2 doses (pregnant)",
    function: "single",
    numerator: { dataElementId: "OrKSwpDxQaJ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "td3__pregnant",
    displayName: "TD3 doses (pregnant)",
    function: "single",
    numerator: { dataElementId: "vMZQxa2plDI", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "tested_hiv",
    displayName: "Tested HIV",
    function: "single",
    numerator: { dataElementId: "vFHITfiDo9g", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "tested_hiv_positive",
    displayName: "Tested HIV positive",
    function: "single",
    numerator: { dataElementId: "B404cBe6vUa", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "contraceptives_female_condom",
    displayName: "Women using female condoms",
    function: "single",
    numerator: { dataElementId: "Onpo1O1A7jr", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "contraceptives_emergency__fp_emergency_all",
    displayName: "Women using oral emergency contraceptives",
    function: "single",
    numerator: { dataElementId: "b2mZpqmL8VB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "contraceptives_oral_lofemenal",
    displayName: "Women using oral lo-femenal contraceptives",
    function: "single",
    numerator: { dataElementId: "dt0srLW7MmK", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "contraceptives_oral_microgynon",
    displayName: "Women using oral microgynon contraceptives",
    function: "single",
    numerator: { dataElementId: "A3r248imZ1L", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "contraceptives_oral_ovrette",
    displayName: "Women using oral ovrette contraceptives",
    function: "single",
    numerator: { dataElementId: "dyfJZ2Llr6F", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },

  {
    key: "contraceptives_oral_other",
    displayName: "Women using other oral contraceptives",
    function: "single",
    numerator: { dataElementId: "NXCJqj7Edfo", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "opd_attendance",
    displayName: "OPD attendance",
    function: "single",
    numerator: {
      dataElementId: "sv6SeKroHPV",
      function: "single",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "GENERAL",
    reportingFrequency: "monthly",
  },

  {
    key: "CHM-001",
    displayName:
      "CHM - Proportion of women in child bearing age using family planning method",
    function: "single",
    numerator: { dataElementId: "qWmp6ar4GSS", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHM-002",
    displayName:
      "CHM - Proportion of Pregnant who attended atleast 4  antenatal care Visits",
    function: "single",
    numerator: { dataElementId: "YWdurab8GUI", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHM-003",
    displayName:
      "CHM - Proportion of Pregnant who attended atleast 8 antenatal care Visits",
    function: "single",
    numerator: { dataElementId: "oUPfUoCx8T5", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHM-004",
    displayName: "CHM - Proportion of  pregnant women who delivered at home",
    function: "single",
    numerator: { dataElementId: "BWa5OKXBnKL", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHM-005",
    displayName:
      "CHM - Proportion of pregnant women who died during pregnancy in the community",
    function: "single",
    numerator: { dataElementId: "LZUjkfqaS6i", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHM-006",
    displayName:
      "CHM - Proportion of pregnant women with danger signs reffered",
    function: "single",
    numerator: { dataElementId: "t4szt7SkmvK", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHM-007",
    displayName: "CHM - Proportion of Pregnant /lactating Women with red MUAC",
    function: "single",
    numerator: { dataElementId: "JXmW20dcD9g", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-001",
    displayName:
      "CHC - Proportion of children less than 1 month  reported dead in the community",
    function: "single",
    numerator: { dataElementId: "ulVTa8n0dg9", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-002",
    displayName:
      "CHC - Proportion of children betweeen  1 month and  11 months   reported dead in the community",
    function: "single",
    numerator: { dataElementId: "YyQbpCGHVLM", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-003",
    displayName:
      "CHC - Proportion of children between  1 year to 5 years who were reported dead in the community",
    function: "single",
    numerator: { dataElementId: "XTtgKWbb33s", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-004",
    displayName:
      "CHC - Proportion of children under 5 years who were reported dead in the community",
    function: "single",
    numerator: { dataElementId: "SQnc564dMyJ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-005",
    displayName:
      "CHC - Propotion of children under who received vitamin A in the last 6 months",
    function: "single",
    numerator: { dataElementId: "hjBYMet9ETI", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-006",
    displayName:
      "CHC - Proportion of Children under five years that were dewormed in the last 6 Months",
    function: "single",
    numerator: { dataElementId: "kIzWZ061Ill", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-007",
    displayName: "CHC - Proportion of Children with red MUAC",
    function: "single",
    numerator: { dataElementId: "YIlcfeW64TE", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-008",
    displayName: "CHC - Propotion of Children with Oedema",
    function: "single",
    numerator: { dataElementId: "mLTfdnIAJSw", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-009",
    displayName:
      "CHC - Propotion of Children with Oedema or red or yellow MUAC who are reffered",
    function: "single",
    numerator: { dataElementId: "Xlgeqv69eW2", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHC-010",
    displayName:
      "CHC - Proportion of children under 5years with up to date immunization",
    function: "single",
    numerator: { dataElementId: "x8pMRKVTDOS", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHC",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHHTB-001",
    displayName:
      "CHHTB - Proportion of HIV positive patients that are not on treatment",
    function: "single",
    numerator: { dataElementId: "E8XlkjxceMj", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHHTB",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHHTB-002",
    displayName:
      "CHHTB - Proportion of TB patients who are not on TB treatment",
    function: "single",
    numerator: { dataElementId: "iWQC5FP1Rmx", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHHTB",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHHTB-003",
    displayName: "CHHTB - Proportion of people who sleep under LLIN",
    function: "single",
    numerator: { dataElementId: "y87CFusc2mJ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHHTB",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHW-001",
    displayName: "CHW - Proportion of households with latrines",
    function: "single",
    numerator: { dataElementId: "yRiGyQaKGcK", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHW",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHW-002",
    displayName: "CHW - Proportion of households with Improved  latrines",
    function: "single",
    numerator: { dataElementId: "BVDdlVEOeQc", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHW",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHW-003",
    displayName: "CHW - Proportion of households with handwashing facilities",
    function: "single",
    numerator: { dataElementId: "Y6yqbwGyNcK", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHW",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHW-004",
    displayName:
      "CHW - Proportion of households with source safe drinking water",
    function: "single",
    numerator: { dataElementId: "E7d7CloQiMS", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHW",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHW-005",
    displayName:
      "CHW - Proportion of households that are open defeacation free",
    function: "single",
    numerator: { dataElementId: "nuhYCiiGmuH", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHW",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-001",
    displayName:
      "CHICCM - Proportion of sick Children 2 months – 5 years seen by VHTs with Diarrhoea in the community",
    function: "single",
    numerator: { dataElementId: "SBxgVBZ0T2b", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-002",
    displayName:
      "CHICCM - Proportion of Sick children 2 months -5yrs seen  by VHT and treated with ORS/Zinc copack  for Diarrhoea in the community",
    function: "single",
    numerator: { dataElementId: "ABuRNqtTQHJ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-003",
    displayName:
      "CHICCM - Proportion of Children 2 months - 5yrs seen by VHT and treated within 24hrs for Diarrhoea in the community",
    function: "single",
    numerator: { dataElementId: "pgooppftLQK", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-004",
    displayName:
      "CHICCM - Proportion of Children 2 months - 5yrs cases with fever seen by VHTs in the community",
    function: "single",
    numerator: { dataElementId: "RHuJknb2sD7", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-005",
    displayName:
      "CHICCM - Proportion of Children 2months - 5yrs cases with fever that received malaria RDT seen by VHTs in the community",
    function: "single",
    numerator: { dataElementId: "hwsCAW8hwZO", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-006",
    displayName:
      "CHICCM - Proportion of Sick Children 2months-5yrs with confirmed Malaria by RDT in the community",
    function: "single",
    numerator: { dataElementId: "KH0dvtNaChi", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-007",
    displayName:
      "CHICCM - Proportion of Sick children 2 months- 5yrs malaria cases that received ACT seen by VHTs in the community",
    function: "single",
    numerator: { dataElementId: "MWsPBMIage8", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-008",
    displayName:
      "CHICCM - Proportion of Sick children 2 months -5yrs with fever + danger sign seen in the community",
    function: "single",
    numerator: { dataElementId: "I1HTSWsnWJF", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-009",
    displayName:
      "CHICCM - Proportion of Sick children 2 months - 5yrs with fever and danger sign treated with rectal artesunate by VHTs",
    function: "single",
    numerator: { dataElementId: "uMtDg4qZ2oX", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-010",
    displayName:
      "CHICCM - Proportion  of Sick children 2 months – 5 years seen by VHT and treated within 24hrs for fever in the community",
    function: "single",
    numerator: { dataElementId: "xVdeHPQQKwl", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-011",
    displayName:
      "CHICCM - Proportion of Sick children who were managed by VHT who recovered",
    function: "single",
    numerator: { dataElementId: "JcuxnUSICw6", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-012",
    displayName:
      "CHICCM - Proportion  of sick Children 2 months – 5 years with fast breathing / Pneumonia",
    function: "single",
    numerator: { dataElementId: "cCWGBZlz3HC", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-013",
    displayName:
      "CHICCM - Proportion of Sick children 2 months - 5yrs confirmed pneumonia  that received amoxicillin dispersible tablets",
    function: "single",
    numerator: { dataElementId: "rNSO5Vup5T5", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-014",
    displayName:
      "CHICCM - Proportion of Sick children 2months - 5yrs seen by VHT and treated within 24hrs for pneumonia",
    function: "single",
    numerator: { dataElementId: "WQSsE382g5f", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHICCM-015",
    displayName:
      "CHICCM - Proportion of sick children under 5 years referred to the Health Unit",
    function: "single",
    numerator: { dataElementId: "dWTxe9qIabU", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHICCM",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHSTOCK-001",
    displayName: "CHSTOCK - Proportion of villages with stock out of the ACT",
    function: "single",
    numerator: { dataElementId: "zxJWUgIuj9U", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHSTOCK",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHSTOCK-002",
    displayName: "CHSTOCK - Proportion of villages with Stock out of RDTs",
    function: "single",
    numerator: { dataElementId: "vNDI3f5tsgw", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHSTOCK",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHSTOCK-003",
    displayName:
      "CHSTOCK - Proportion of villages with stock out of rectal Artesunate",
    function: "single",
    numerator: { dataElementId: "auoxfH4Zd0I", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHSTOCK",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHSTOCK-004",
    displayName:
      "CHSTOCK - Proportion of villages with Stock out of Amoxycillin",
    function: "single",
    numerator: { dataElementId: "uQvu8YoYATz", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHSTOCK",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHSTOCK-005",
    displayName: "CHSTOCK - Proportion of villages with stock out of ORS+ Zinc",
    function: "single",
    numerator: { dataElementId: "ru3AnD3BORA", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHSTOCK",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHSTOCK-006",
    displayName:
      "CHSTOCK - Proportion of villages with Stock out of Misoprostol",
    function: "single",
    numerator: { dataElementId: "AxmRemQZ1Ve", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHSTOCK",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHFP-001",
    displayName:
      "CHFP - Proportion of villages with Stock out of Injectable DMPA",
    function: "single",
    numerator: { dataElementId: "Kg5Znm1bTU5", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHFP",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHFP-002",
    displayName:
      "CHFP - Proportion of villages with Stock out of Combined Oral Contraceptive",
    function: "single",
    numerator: { dataElementId: "kaYaDO3oOMb", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHFP",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHFP-003",
    displayName: "CHFP - Proportion of villages with Stock out of Condoms",
    function: "single",
    numerator: { dataElementId: "QEspB5XVXVV", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHFP",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHFP-004",
    displayName:
      "CHFP - Proportion of villages with  stock out of Progestin Only Pills",
    function: "single",
    numerator: { dataElementId: "dDOwE0917GX", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHFP",
    reportingFrequency: "quarterly",
  },
  {
    key: "CHFP-005",
    displayName:
      "CHFP - Proportion of villages with stock out of Emergency Contraceptives",
    function: "single",
    numerator: { dataElementId: "R1juTYAlQcq", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "CHFP",
    reportingFrequency: "quarterly",
  },

  {
    key: "11109",
    displayName: "1st & 2nd doses of vitamin A to female U5",
    function: "nansum",
    numerator: {
      dataElementId: ["vI52cxgsBNv", "A2ZOozUNmDz"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
  },
  {
    key: "11110",
    displayName: "1st & 2nd doses of vitamin A to male U5",
    function: "nansum",
    numerator: {
      dataElementId: ["vI52cxgsBNv", "A2ZOozUNmDz"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
  },
  {
    key: "11111",
    displayName: "1st & 2nd doses of vitamin A to U5",
    function: "nansum",
    numerator: {
      dataElementId: ["vI52cxgsBNv", "A2ZOozUNmDz"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
  },
  {
    key: "11112",
    displayName: "Low weight births",
    function: "nansum",
    numerator: {
      dataElementId: ["MzqiroyuhJh", "bl6lQqygEK1", "P1MyPWVxi5T"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
  },
  {
    key: "11113",
    displayName: "Malaria cases treated",
    function: "nansum",
    numerator: {
      dataElementId: [
        "PV8F3aPDKCu",
        "YBXFadujBCQ",
        "qR6OsOxADKt",
        "sDDBGMsrw6z",
        "S97lGebltuo",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "MAL",
    reportingFrequency: "monthly",
  },
  {
    key: "11114",
    displayName: "Malaria tests",
    function: "nansum",
    numerator: {
      dataElementId: ["lQXr10kZXrB", "RGDv14C4Cdw"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "MAL",
    reportingFrequency: "monthly",
  },
  {
    key: "11115",
    displayName: "MAM cases identified",
    function: "nansum",
    numerator: {
      dataElementId: ["zm2QCkywpqX", "zm2QCkywpqX"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
  },
  {
    key: "11116",
    displayName: "Mat tested HIV",
    function: "nansum",
    numerator: {
      dataElementId: ["SPctnmpC7W6", "lqlyPEh4beG"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "11117",
    displayName: "Mat tested HIV positive",
    function: "nansum",
    numerator: {
      dataElementId: ["AUfFbS7cWFd", "jHqJsOlZWZG"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "11118",
    displayName: "Mothers initiated on ART",
    function: "nansum",
    numerator: {
      dataElementId: ["L4pwIgSDdG6", "KDoEmOjpYnL", "kGC9MVJppnk"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "11119",
    displayName: "Mothers tested for HIV",
    function: "nansum",
    numerator: {
      dataElementId: [
        "uALBQG7TFhq",
        "SPctnmpC7W6",
        "lqlyPEh4beG",
        "L0kzvUuDu0M",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "11120",
    displayName: "Mothers tested HIV-positive",
    function: "nansum",
    numerator: {
      dataElementId: [
        "uzlQdD84jNj",
        "AUfFbS7cWFd",
        "jHqJsOlZWZG",
        "eerKMtKyYZt",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
    reportingFrequency: "monthly",
  },
  {
    key: "11122",
    displayName: "SAM cases identified",
    function: "nansum",
    numerator: {
      dataElementId: ["dgnUFBzt87d", "LX6uCvQ7a7W", "zvJyAAeman2"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
  },
  {
    key: "11123",
    displayName: "TB cases registered in treatment unit (females)",
    function: "nansum",
    numerator: {
      dataElementId: [
        "vSaFiVhebVQ.'bdbxoGD7oAY",
        "vSaFiVhebVQ.EJn0qutf2Uh",
        "vSaFiVhebVQ.Q29KLru4s67",
        "vSaFiVhebVQ.SPvm3s5w8ZJ",
        "vSaFiVhebVQ.n5YvcIzcYaF",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "11124",
    displayName: "TB cases registered in treatment unit (males)",
    function: "nansum",
    numerator: {
      dataElementId: ["vSaFiVhebVQ.EVJwOnx0wy9", "vSaFiVhebVQ"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "11125",
    displayName: "TD4-5 doses (nonpregnant)",
    function: "nansum",
    numerator: {
      dataElementId: [
        "Jd24EcGuIvS.ti1wQxWVB4m",
        "Jd24EcGuIvS.HFZpUNRdkVF",
        "fyTVWlH6jqm.zBEtAxHIaIx",
        "fyTVWlH6jqm.QzcaaLV5dVM",
        "fyTVWlH6jqm.UShugsidUxz",
        "fyTVWlH6jqm.MJzZmZ3OMxI",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "11126",
    displayName: "TD4-5 doses (pregnant)",
    function: "nansum",
    numerator: {
      dataElementId: [
        "Jd24EcGuIvS.OnvxZRXJz9g",
        "Jd24EcGuIvS.KEONQZzpUjz",
        "fyTVWlH6jqm",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
  },
  {
    key: "11127",
    displayName: "Women using injectable contraceptives",
    function: "nansum",
    numerator: {
      dataElementId: [
        "ZVKD2XRg6Ab",
        "Fat3y7a43qY",
        "iodD0RgSRoD",
        "O3dDxoUjSqo",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "11128",
    displayName: "Women using injectable contraceptives (under 20)",
    function: "nansum",
    numerator: {
      dataElementId: [
        "ZVKD2XRg6Ab.HTMSuJ2wUcx",
        "ZVKD2XRg6Ab.YpZHGtTSv2K",
        "ZVKD2XRg6Ab.ksBfihkwBeu",
        "ZVKD2XRg6Ab.BhgBkEr8t85",
        "ZVKD2XRg6Ab.n51tcnorjjQ",
        "ZVKD2XRg6Ab.JkUnZbGFfjK",
        "Fat3y7a43qY.HTMSuJ2wUcx",
        "Fat3y7a43qY.YpZHGtTSv2K",
        "Fat3y7a43qY.ksBfihkwBeu",
        "Fat3y7a43qY.BhgBkEr8t85",
        "Fat3y7a43qY.n51tcnorjjQ",
        "Fat3y7a43qY.JkUnZbGFfjK",
        "iodD0RgSRoD.HTMSuJ2wUcx",
        "iodD0RgSRoD.YpZHGtTSv2K",
        "iodD0RgSRoD.ksBfihkwBeu",
        "iodD0RgSRoD.BhgBkEr8t85",
        "iodD0RgSRoD.n51tcnorjjQ",
        "iodD0RgSRoD.JkUnZbGFfjK",
        "O3dDxoUjSqo.HTMSuJ2wUcx",
        "O3dDxoUjSqo.YpZHGtTSv2K",
        "O3dDxoUjSqo.ksBfihkwBeu",
        "O3dDxoUjSqo.BhgBkEr8t85",
        "O3dDxoUjSqo.n51tcnorjjQ",
        "O3dDxoUjSqo.JkUnZbGFfjK",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "11129",
    displayName: "Women using iuds",
    function: "nansum",
    numerator: {
      dataElementId: ["jSQRBvez5Pq", "zhTC6HT9No1"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "11130",
    displayName: "Women using iuds (under 20)",
    function: "nansum",
    numerator: {
      dataElementId: [
        "jSQRBvez5Pq.HTMSuJ2wUcx",
        "jSQRBvez5Pq.YpZHGtTSv2K",
        "jSQRBvez5Pq.ksBfihkwBeu",
        "jSQRBvez5Pq.BhgBkEr8t85",
        "jSQRBvez5Pq.n51tcnorjjQ",
        "jSQRBvez5Pq.JkUnZbGFfjK",
        "zhTC6HT9No1.HTMSuJ2wUcx",
        "zhTC6HT9No1.YpZHGtTSv2K",
        "zhTC6HT9No1.ksBfihkwBeu",
        "zhTC6HT9No1.BhgBkEr8t85",
        "zhTC6HT9No1.n51tcnorjjQ",
        "zhTC6HT9No1.JkUnZbGFfjK",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "11131",
    displayName: "Women using natural contraception methods",
    function: "nansum",
    numerator: {
      dataElementId: ["VHi82Mcd77w", "ibfLXaygcNS", "HnSiI2XX2Sy"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "11132",
    displayName: "Women using natural contraception methods (under 20)",
    function: "nansum",
    numerator: {
      dataElementId: [
        "VHi82Mcd77w.HTMSuJ2wUcx",
        "VHi82Mcd77w.YpZHGtTSv2K",
        "VHi82Mcd77w.ksBfihkwBeu",
        "VHi82Mcd77w.BhgBkEr8t85",
        "VHi82Mcd77w.n51tcnorjjQ",
        "VHi82Mcd77w.JkUnZbGFfjK",
        "ibfLXaygcNS.HTMSuJ2wUcx",
        "ibfLXaygcNS.YpZHGtTSv2K",
        "ibfLXaygcNS.ksBfihkwBeu",
        "ibfLXaygcNS.BhgBkEr8t85",
        "ibfLXaygcNS.n51tcnorjjQ",
        "ibfLXaygcNS.JkUnZbGFfjK",
        "HnSiI2XX2Sy.HTMSuJ2wUcx",
        "HnSiI2XX2Sy.YpZHGtTSv2K",
        "HnSiI2XX2Sy.ksBfihkwBeu",
        "HnSiI2XX2Sy.BhgBkEr8t85",
        "HnSiI2XX2Sy.n51tcnorjjQ",
        "HnSiI2XX2Sy.JkUnZbGFfjK",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "11133",
    displayName: "Women using oral contraceptives - excl. Levono",
    function: "nansum",
    numerator: {
      dataElementId: [
        "NXCJqj7Edfo",
        "A3r248imZ1L",
        "dt0srLW7MmK",
        "dyfJZ2Llr6F",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
  {
    key: "11134",
    displayName: "Women using oral contraceptives - excl. Levono (under 20)",
    function: "nansum",
    numerator: {
      dataElementId: [
        "NXCJqj7Edfo.HTMSuJ2wUcx",
        "NXCJqj7Edfo.YpZHGtTSv2K",
        "NXCJqj7Edfo.ksBfihkwBeu",
        "NXCJqj7Edfo.BhgBkEr8t85",
        "NXCJqj7Edfo.n51tcnorjjQ",
        "NXCJqj7Edfo.JkUnZbGFfjK",
        "A3r248imZ1L.HTMSuJ2wUcx",
        "A3r248imZ1L.YpZHGtTSv2K",
        "A3r248imZ1L.ksBfihkwBeu",
        "A3r248imZ1L.BhgBkEr8t85",
        "A3r248imZ1L.n51tcnorjjQ",
        "A3r248imZ1L.JkUnZbGFfjK",
        "dt0srLW7MmK.HTMSuJ2wUcx",
        "dt0srLW7MmK.YpZHGtTSv2K",
        "dt0srLW7MmK.ksBfihkwBeu",
        "dt0srLW7MmK.BhgBkEr8t85",
        "dt0srLW7MmK.n51tcnorjjQ",
        "dt0srLW7MmK.JkUnZbGFfjK",
        "dyfJZ2Llr6F.HTMSuJ2wUcx",
        "dyfJZ2Llr6F.YpZHGtTSv2K",
        "dyfJZ2Llr6F.ksBfihkwBeu",
        "dyfJZ2Llr6F.BhgBkEr8t85",
        "dyfJZ2Llr6F.n51tcnorjjQ",
        "dyfJZ2Llr6F.JkUnZbGFfjK",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
  },
];

export default indicatorMeta;
