const indicatorMeta = [
  {
    key: "1st_anc_visits",
    displayName: "1st ANC Visits",
    function: "single",
    numerator: { dataElementId: "Q9nSogNmKPt", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "vitamin_a1",
    displayName: "1st doses of vitamin A to U5",
    function: "single",
    numerator: { dataElementId: "vI52cxgsBNv", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },
  {
    key: "vitamin_a2",
    displayName: "2nd doses of vitamin A to U5",
    function: "single",
    numerator: { dataElementId: "A2ZOozUNmDz", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },
  {
    key: "4th_anc_visits",
    displayName: "4th ANC Visits",
    function: "single",
    numerator: { dataElementId: "RnLOFSYaAhp", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "abortions_other",
    displayName: "Abortions not related to GBV",
    function: "single",
    numerator: { dataElementId: "FlRxDBHWGid", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "abortions_gbv",
    displayName: "Abortions related to GBV",
    function: "single",
    numerator: { dataElementId: "TvqHbq8AKc7", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "anc_initiated_hiv",
    displayName: "ANC initiated on ART",
    function: "single",
    numerator: { dataElementId: "L4pwIgSDdG6", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "anc_tested_hiv",
    displayName: "ANC tested HIV",
    function: "single",
    numerator: { dataElementId: "uALBQG7TFhq", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "anc_tested_hiv_positive",
    displayName: "ANC tested HIV positive",
    function: "single",
    numerator: { dataElementId: "uzlQdD84jNj", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "bcg",
    displayName: "BCG doses to U1",
    function: "single",
    numerator: { dataElementId: "MxAg9De4cra", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "bcg__u1_outreach",
    displayName: "BCG doses to U1 (outreach)",
    function: "single",
    numerator: { dataElementId: "MxAg9De4cra", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "bcg__u1_static",
    displayName: "BCG doses to U1 (static)",
    function: "nansum",
    numerator: { dataElementId: "MxAg9De4cra", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "births",
    displayName: "Deliveries in unit",
    function: "single",
    numerator: { dataElementId: "idXOxt69W0e", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "births_fresh_stillbirth",
    displayName: "Deliveries in unit - fresh stillbirth",
    function: "single",
    numerator: { dataElementId: "T8W0wbzErSF", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "births_live",
    displayName: "Deliveries in unit - live",
    function: "single",
    numerator: { dataElementId: "fEz9wGsA6YU", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "births_macerated_stillbirth",
    displayName: "Deliveries in unit - macerated stillbirth",
    function: "single",
    numerator: { dataElementId: "ULL9lX3DO7V", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "dpt1",
    displayName: "DPT1 doses to U1",
    function: "single",
    numerator: { dataElementId: "Ys31ug5E3f1", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },

  {
    key: "dpt3",
    displayName: "DPT3 doses to U1",
    function: "single",
    numerator: { dataElementId: "ujs4ipzA4tb", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },

  {
    key: "hiv_positive_linked",
    displayName: "HIV positive linked to care",
    function: "single",
    numerator: { dataElementId: "VmVKCCYeHiF", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "hei_given_arv",
    displayName: "HIV-exposed infants receiving ARV",
    function: "single",
    numerator: { dataElementId: "OUGMxrtXxri", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "hiv_positive_mother_before_anc",
    displayName: "HIV-positive mothers aware of their status before ANC1",
    function: "single",
    numerator: { dataElementId: "b78oMBcC5R8", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "hpv1",
    displayName: "HPV1 doses to girls",
    function: "single",
    numerator: { dataElementId: "Gtk7tbHfVfj", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "hpv1__community",
    displayName: "HPV1 doses to girls (community)",
    function: "single",
    numerator: { dataElementId: "Gtk7tbHfVfj", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "hpv1__school",
    displayName: "HPV1 doses to U1 (school)",
    function: "single",
    numerator: { dataElementId: "Gtk7tbHfVfj", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "hpv2",
    displayName: "HPV2 doses to girls",
    function: "single",
    numerator: { dataElementId: "zcT0YplhdAB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "injuries_gbv",
    displayName: "Injuries related to GBV",
    function: "single",
    numerator: { dataElementId: "bRYoCXTmJCB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "ipd_attendance",
    displayName: "IPD attendance",
    function: "single",
    numerator: { dataElementId: "UwnR5kr982Y", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "GENERAL",
  },
  {
    key: "malaria_cases",
    displayName: "Malaria cases",
    function: "single",
    numerator: { dataElementId: "fUflbWWhouR", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MAL",
  },
  {
    key: "malaria_deaths",
    displayName: "Malaria deaths",
    function: "single",
    numerator: { dataElementId: "IoZCByEDSnX", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MAL",
  },
  {
    key: "mat_initiated_hiv",
    displayName: "Mat initiated on ART",
    function: "single",
    numerator: { dataElementId: "KDoEmOjpYnL", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "maternal_deaths",
    displayName: "Maternal deaths",
    function: "single",
    numerator: { dataElementId: "F8Iz6QcexWB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "maternal_deaths__a20",
    displayName: "Maternal deaths (above 20)",
    function: "single",
    numerator: { dataElementId: "F8Iz6QcexWB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "maternal_deaths__u20",
    displayName: "Maternal deaths (under 20)",
    function: "single",
    numerator: { dataElementId: "F8Iz6QcexWB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "maternity_admissions",
    displayName: "Maternity Admissions",
    function: "single",
    numerator: { dataElementId: "JY0M7eC2N42", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "contraceptives_male_condom",
    displayName: "Men using male condoms",
    function: "single",
    numerator: { dataElementId: "bkCFVYMFMed", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },

  {
    key: "breastfed_1st_hour",
    displayName: "Mothers breastfeeding after delivery",
    function: "single",
    numerator: { dataElementId: "XXZZbU4B2N3", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "mr1",
    displayName: "MR1 doses to U1",
    function: "single",
    numerator: { dataElementId: "WAjgHQVxVVm", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },

  {
    key: "newborn_deaths",
    displayName: "Newborn deaths",
    function: "single",
    numerator: { dataElementId: "hrTskGHP0Av", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "pcv1",
    displayName: "PCV1 doses to U1",
    function: "single",
    numerator: { dataElementId: "NbG01i1Md55", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "pcv3",
    displayName: "PCV3 doses to U1",
    function: "single",
    numerator: { dataElementId: "QHawVF72X6E", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },

  {
    key: "pnc_initiated_hiv",
    displayName: "PNC initiated on ART",
    function: "single",
    numerator: { dataElementId: "kGC9MVJppnk", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "pnc_tested_hiv",
    displayName: "PNC tested HIV",
    function: "single",
    numerator: { dataElementId: "L0kzvUuDu0M", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "pnc_tested_hiv_positive",
    displayName: "PNC tested HIV positive",
    function: "single",
    numerator: { dataElementId: "eerKMtKyYZt", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "postnatal_visits",
    displayName: "Postnatal Visits",
    function: "single",
    numerator: { dataElementId: "LJ8MLXHctGs", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "MNCH",
  },
  {
    key: "sti_other",
    displayName: "STI cases not related to SGBV",
    function: "single",
    numerator: { dataElementId: "KaqDbaq0Yce", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "sti_gbv",
    displayName: "STI cases related to SGBV",
    function: "single",
    numerator: { dataElementId: "Cw3RNymXWjr", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "tb_cases_registered",
    displayName: "TB cases registered in treatment unit",
    function: "single",
    numerator: { dataElementId: "vSaFiVhebVQ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "td1__nonpregnant",
    displayName: "TD1 doses (nonpregnant)",
    function: "single",
    numerator: { dataElementId: "oj4ttY118Fg", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "td2__pregnant",
    displayName: "TD2 doses (pregnant)",
    function: "single",
    numerator: { dataElementId: "OrKSwpDxQaJ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "td3__nonpregnant",
    displayName: "TD3 doses (nonpregnant)",
    function: "nansum",
    numerator: { dataElementId: "vMZQxa2plDI", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "td3__pregnant",
    displayName: "TD3 doses (pregnant)",
    function: "single",
    numerator: { dataElementId: "vMZQxa2plDI", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "tested_hiv",
    displayName: "Tested HIV",
    function: "single",
    numerator: { dataElementId: "vFHITfiDo9g", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "tested_hiv_positive",
    displayName: "Tested HIV positive",
    function: "single",
    numerator: { dataElementId: "B404cBe6vUa", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "contraceptives_female_condom",
    displayName: "Women using female condoms",
    function: "single",
    numerator: { dataElementId: "Onpo1O1A7jr", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "contraceptives_emergency__fp_emergency_all",
    displayName: "Women using oral emergency contraceptives",
    function: "single",
    numerator: { dataElementId: "b2mZpqmL8VB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "contraceptives_oral_lofemenal",
    displayName: "Women using oral lo-femenal contraceptives",
    function: "single",
    numerator: { dataElementId: "dt0srLW7MmK", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "contraceptives_oral_microgynon",
    displayName: "Women using oral microgynon contraceptives",
    function: "single",
    numerator: { dataElementId: "A3r248imZ1L", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "contraceptives_oral_microgynon__fp_contraception_u20",
    displayName: "Women using oral microgynon contraceptives (under 20)",
    function: "nansum",
    numerator: { dataElementId: "A3r248imZ1L", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "contraceptives_oral_ovrette",
    displayName: "Women using oral ovrette contraceptives",
    function: "single",
    numerator: { dataElementId: "dyfJZ2Llr6F", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "contraceptives_oral_other",
    displayName: "Women using other oral contraceptives",
    function: "single",
    numerator: { dataElementId: "NXCJqj7Edfo", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },

  {
    key: "11111",
    displayName: "1st & 2nd doses of vitamin A to U5",
    function: "nansum",
    numerator: {
      dataElementId: ["vI52cxgsBNv", "A2ZOozUNmDz"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },
  {
    key: "11112",
    displayName: "Low weight births",
    function: "nansum",
    numerator: {
      dataElementId: [["MzqiroyuhJh", "bl6lQqygEK1", "P1MyPWVxi5T"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },
  {
    key: "11113",
    displayName: "Malaria cases treated",
    function: "nansum",
    numerator: {
      dataElementId: [
        [
          "PV8F3aPDKCu",
          "YBXFadujBCQ",
          "qR6OsOxADKt",
          "sDDBGMsrw6z",
          "S97lGebltuo",
        ],
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "MAL",
  },
  {
    key: "11114",
    displayName: "Malaria tests",
    function: "nansum",
    numerator: {
      dataElementId: [["lQXr10kZXrB", "RGDv14C4Cdw"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "MAL",
  },
  {
    key: "11115",
    displayName: "MAM cases identified",
    function: "nansum",
    numerator: {
      dataElementId: [["zm2QCkywpqX", "zm2QCkywpqX"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },
  {
    key: "11116",
    displayName: "Mat tested HIV",
    function: "nansum",
    numerator: {
      dataElementId: [["SPctnmpC7W6", "lqlyPEh4beG"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "11117",
    displayName: "Mat tested HIV positive",
    function: "nansum",
    numerator: {
      dataElementId: [["AUfFbS7cWFd", "jHqJsOlZWZG"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "11118",
    displayName: "Mothers initiated on ART",
    function: "nansum",
    numerator: {
      dataElementId: ["L4pwIgSDdG6", "KDoEmOjpYnL", "kGC9MVJppnk"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "11119",
    displayName: "Mothers tested for HIV",
    function: "nansum",
    numerator: {
      dataElementId: [
        "uALBQG7TFhq",
        ["SPctnmpC7W6", "lqlyPEh4beG"],
        "L0kzvUuDu0M",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "11120",
    displayName: "Mothers tested HIV-positive",
    function: "nansum",
    numerator: {
      dataElementId: [
        "uzlQdD84jNj",
        ["AUfFbS7cWFd", "jHqJsOlZWZG"],
        "eerKMtKyYZt",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "HIV",
  },
  {
    key: "11121",
    displayName: "OPD attendance",
    function: "nansum",
    numerator: {
      dataElementId: [["sv6SeKroHPV", "sQ4EexvvhVe"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "GENERAL",
  },
  {
    key: "11122",
    displayName: "SAM cases identified",
    function: "nansum",
    numerator: {
      dataElementId: [["dgnUFBzt87d", "LX6uCvQ7a7W", "zvJyAAeman2"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },
  {
    key: "11123",
    displayName: "TB cases registered in treatment unit (females)",
    function: "nansum",
    numerator: {
      dataElementId: ["vSaFiVhebVQ", "vSaFiVhebVQ"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "11124",
    displayName: "TB cases registered in treatment unit (males)",
    function: "nansum",
    numerator: {
      dataElementId: ["vSaFiVhebVQ", "vSaFiVhebVQ"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "11125",
    displayName: "TD4-5 doses (nonpregnant)",
    function: "nansum",
    numerator: {
      dataElementId: [["Jd24EcGuIvS", "fyTVWlH6jqm"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "11126",
    displayName: "TD4-5 doses (pregnant)",
    function: "nansum",
    numerator: {
      dataElementId: [["Jd24EcGuIvS", "fyTVWlH6jqm"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "11127",
    displayName: "Women using injectable contraceptives",
    function: "nansum",
    numerator: {
      dataElementId: [
        ["ZVKD2XRg6Ab", " Fat3y7a43qY", "iodD0RgSRoD", "O3dDxoUjSqo"],
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "11128",
    displayName: "Women using injectable contraceptives (under 20)",
    function: "nansum",
    numerator: {
      dataElementId: [
        ["ZVKD2XRg6Ab", "Fat3y7a43qY", "iodD0RgSRoD", "O3dDxoUjSqo"],
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "11129",
    displayName: "Women using iuds",
    function: "nansum",
    numerator: {
      dataElementId: [["jSQRBvez5Pq", "zhTC6HT9No1"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "11130",
    displayName: "Women using iuds (under 20)",
    function: "nansum",
    numerator: {
      dataElementId: [["jSQRBvez5Pq", "zhTC6HT9No2"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "11131",
    displayName: "Women using natural contraception methods",
    function: "nansum",
    numerator: {
      dataElementId: [["VHi82Mcd77w", "ibfLXaygcNS", "HnSiI2XX2Sy"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "11132",
    displayName: "Women using natural contraception methods (under 20)",
    function: "nansum",
    numerator: {
      dataElementId: [["VHi82Mcd77w", "ibfLXaygcNS", "HnSiI2XX2Sy"]],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "11133",
    displayName: "Women using oral contraceptives - excl. Levono",
    function: "nansum",
    numerator: {
      dataElementId: [
        "NXCJqj7Edfo",
        "A3r248imZ1L",
        "dt0srLW7MmK",
        "dyfJZ2Llr6F",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "11134",
    displayName: "Women using oral contraceptives - excl. Levono (under 20)",
    function: "nansum",
    numerator: {
      dataElementId: [
        "NXCJqj7Edfo",
        "A3r248imZ1L",
        "dt0srLW7MmK",
        "dyfJZ2Llr6F",
      ],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },

  // ====
  {
    key: "220",
    displayName: "VHT density ",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: null,
  },
  {
    key: "221",
    displayName: "Proportion of House hold members seen with hypertension ",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: null,
  },
  {
    key: "222",
    displayName: "Proportion of House holds using  Drugs (Tobacco ,drug use ",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: null,
  },
  {
    key: "223",
    displayName: "Reporting Rate of VHT/ICCM 097B ",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: null,
  },
  {
    key: "224",
    displayName: "Proportion of VHTs with Phones ",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: null,
  },
  {
    key: "225",
    displayName:
      "Proportion of women in child bearing age using family planning method",
    function: "ratio",
    numerator: { dataElementId: "S3IEND4xk3D", function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "Maternal",
  },
  {
    key: "226",
    displayName:
      "Proportion of Pregnant who attended atleast 4  antenatal care Visits ",
    function: "ratio",
    numerator: { dataElementId: "m47w1ABKkOQ", function: "nansum" },
    denominator: { dataElementId: "qaBd9CL3BdC", function: "nansum" },
    group: "Maternal",
  },
  {
    key: "227",
    displayName:
      "Proportion of Pregnant who attended atleast 8 antenatal care Visits ",
    function: "ratio",
    numerator: { dataElementId: "T5MYv4SQNfm", function: "nansum" },
    denominator: { dataElementId: "qaBd9CL3BdC", function: "nansum" },
    group: "Maternal",
  },
  {
    key: "228",
    displayName: "Proportion of  pregnant women who delivered at home",
    function: "ratio",
    numerator: { dataElementId: "V1PUCQMdycO", function: "nansum" },
    denominator: { dataElementId: "qaBd9CL3BdC", function: "nansum" },
    group: "Maternal",
  },
  {
    key: "229",
    displayName:
      "Proportion of pregnant women who died during pregnancy in the community",
    function: "ratio",
    numerator: { dataElementId: "UfF8EONTbBA", function: "nansum" },
    denominator: { dataElementId: "qaBd9CL3BdC", function: "nansum" },
    group: "Maternal",
  },
  {
    key: "2210",
    displayName: "Proportion of pregnant women with reffered",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "Maternal",
  },
  {
    key: "2211",
    displayName:
      "Proportion of women who attend atleast one postpartum check within 6 weeks ",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "Maternal",
  },
  {
    key: "2212",
    displayName: "Proportion of Pregnant /lactating Women with red MUAC ",
    function: "ratio",
    numerator: { dataElementId: "jUPnBztfymC", function: "nansum" },
    denominator: { dataElementId: "qaBd9CL3BdC", function: "nansum" },
    group: "Maternal",
  },
  {
    key: "2213",
    displayName:
      "Proportion of children less than 1 month  reported dead in the community",
    function: "ratio",
    numerator: { dataElementId: "eCKBhAF0ROc", function: "nansum" },
    denominator: { dataElementId: "xHMSX6jXfcU", function: "nansum" },
    group: "Children",
  },
  {
    key: "2214",
    displayName:
      "Proportion of children betweeen  1 month and  11 months   reported dead in the community",
    function: "ratio",
    numerator: { dataElementId: "MF7OJNXuQFt", function: "nansum" },
    denominator: { dataElementId: "rJlqR6EAhGh", function: "nansum" },
    group: "Children",
  },
  {
    key: "2215",
    displayName:
      "Proportion of children between  1 year to 5 years who were reported dead in the community",
    function: "ratio",
    numerator: { dataElementId: "wfhoHgHafZg", function: "nansum" },
    denominator: { dataElementId: "EyHAD6PUZdG", function: "nansum" },
    group: "Children",
  },
  {
    key: "2216",
    displayName:
      "Proportion of children under 5 years who were reported dead in the community",
    function: "ratio",
    numerator: {
      dataElementId: "[eCKBhAF0ROc, MF7OJNXuQFt, wfhoHgHafZg]",
      function: "nansum",
    },
    denominator: { dataElementId: "YKmmdBwdmLL", function: "nansum" },
    group: "Children",
  },
  {
    key: "2217",
    displayName:
      "Propotion of children under who received vitamin A in the last 6 months",
    function: "ratio",
    numerator: { dataElementId: "L1bgdL5dIKS", function: "nansum" },
    denominator: { dataElementId: "YKmmdBwdmLL", function: "nansum" },
    group: "Children",
  },
  {
    key: "2218",
    displayName:
      "Proportion of Children under five years that were dewormed in the last 6 Months",
    function: "ratio",
    numerator: { dataElementId: "znpvMuF8zxr", function: "nansum" },
    denominator: { dataElementId: "YKmmdBwdmLL", function: "nansum" },
    group: "Children",
  },
  {
    key: "2219",
    displayName: "Propotion of Children with red MUAC",
    function: "ratio",
    numerator: { dataElementId: "fIssfXg7cqF", function: "nansum" },
    denominator: { dataElementId: "YKmmdBwdmLL", function: "nansum" },
    group: "Children",
  },
  {
    key: "2220",
    displayName: "Propotion of Children with Oedema",
    function: "ratio",
    numerator: { dataElementId: "dEZHwOBJTez", function: "nansum" },
    denominator: { dataElementId: "YKmmdBwdmLL", function: "nansum" },
    group: "Children",
  },
  {
    key: "2221",
    displayName:
      "Propotion of Children with Oedema or red or yellow MUAC who are reffered ",
    function: "ratio",
    numerator: { dataElementId: "AHbZxta3gab", function: "nansum" },
    denominator: { dataElementId: "tsEsYwfaZ9Z", function: "nansum" },
    group: "Children",
  },
  {
    key: "2222",
    displayName:
      "Proportion of children under 5years with up to date immunization",
    function: "ratio",
    numerator: { dataElementId: "FK2DhZFyudF", function: "nansum" },
    denominator: { dataElementId: "YKmmdBwdmLL", function: "nansum" },
    group: "Children",
  },
  {
    key: "2223",
    displayName:
      "Proportion of adolescents and young people who received HPV Vaccine",
    function: "ratio",
    numerator: { dataElementId: "PEMWQf998zn", function: "nansum" },
    denominator: { dataElementId: "fq2nuotGDUo", function: "nansum" },
    group: "Adolescent Health",
  },
  {
    key: "2224",
    displayName:
      "Proportion of adolescents and young people who received TD Vaccine",
    function: "ratio",
    numerator: { dataElementId: "PX93qDYtZGZ", function: "nansum" },
    denominator: { dataElementId: "fq2nuotGDUo", function: "nansum" },
    group: "Adolescent Health",
  },
  {
    key: "2225",
    displayName:
      "Proportion of HIV positive patients that are not on treatment",
    function: "ratio",
    numerator: { dataElementId: "Aj3u6Ogwywx", function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "HIV & TB",
  },
  {
    key: "2226",
    displayName: "Proportion of TB patients who are not on TB treatment",
    function: "ratio",
    numerator: { dataElementId: "DTVXdGz8hvu", function: "nansum" },
    denominator: { dataElementId: "X7aFDxmFJeK", function: "nansum" },
    group: "HIV & TB",
  },
  {
    key: "2227",
    displayName: "Proportion of people who sleep under LLIN",
    function: "ratio",
    numerator: { dataElementId: "BUlYKu6MgP9", function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "HIV & TB",
  },
  {
    key: "2228",
    displayName: "Proportion of households with latrines",
    function: "ratio",
    numerator: { dataElementId: "vHwo9oXkDVA", function: "nansum" },
    denominator: { dataElementId: "lBNoFDQFSof", function: "nansum" },
    group: "WASH",
  },
  {
    key: "2229",
    displayName: "Proportion of households with Improved  latrines ",
    function: "ratio",
    numerator: { dataElementId: "spZ7lrYcxYZ", function: "nansum" },
    denominator: { dataElementId: "lBNoFDQFSof", function: "nansum" },
    group: "WASH",
  },
  {
    key: "2230",
    displayName: "Proportion of households with handwashing facilities ",
    function: "ratio",
    numerator: { dataElementId: "M6XkYkjhkAK", function: "nansum" },
    denominator: { dataElementId: "lBNoFDQFSof", function: "nansum" },
    group: "WASH",
  },
  {
    key: "2231",
    displayName: "Proportion of households with source safe drinking water  ",
    function: "ratio",
    numerator: { dataElementId: "JG1RuXvH2KQ", function: "nansum" },
    denominator: { dataElementId: "lBNoFDQFSof", function: "nansum" },
    group: "WASH",
  },
  {
    key: "2232",
    displayName: "Proportion of households that are open defeacation free ",
    function: "ratio",
    numerator: { dataElementId: "V1ORAMjlUjS", function: "nansum" },
    denominator: { dataElementId: "lBNoFDQFSof", function: "nansum" },
    group: "WASH",
  },
  {
    key: "2233",
    displayName:
      "Proportion of sick Children 2 months - 5 years seen by VHTs with Diarrhoea in the community",
    function: "ratio",
    numerator: { dataElementId: "GMSs1iHBP1B", function: "nansum" },
    denominator: { dataElementId: "lA61RMKevuI", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2234",
    displayName:
      "Proportion of Sick children 2 months -5yrs seen  by VHT and treated with ORS/Zinc copack  for Diahorrea in the community",
    function: "ratio",
    numerator: { dataElementId: "bdzm4uraecc", function: "nansum" },
    denominator: { dataElementId: "GMSs1iHBP1B", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2235",
    displayName:
      "Proportion of Children 2 months - 5yrs seen by VHT and treated within 24hrs for Diarrhoea in the community",
    function: "ratio",
    numerator: { dataElementId: "fzLZ3QH1XWP", function: "nansum" },
    denominator: { dataElementId: "GMSs1iHBP1B", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2236",
    displayName:
      "Proportion of Children 2 months - 5yrs cases with fever seen by VHTs in the community",
    function: "ratio",
    numerator: { dataElementId: "ZPgTzBpXQtT", function: "nansum" },
    denominator: { dataElementId: "lA61RMKevuI", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2237",
    displayName:
      "Proportion of Children 2months - 5yrs cases with fever that received malaria RDT seen by VHTs in the community",
    function: "ratio",
    numerator: { dataElementId: "SZOxZEnWtGU", function: "nansum" },
    denominator: { dataElementId: "ZPgTzBpXQtT", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2238",
    displayName:
      "Proportion of Sick Children 2months-5yrs with confirmed Malaria by RDT in the community",
    function: "ratio",
    numerator: { dataElementId: "SZOxZEnWtGU", function: "nansum" },
    denominator: { dataElementId: "SZOxZEnWtGU", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2239",
    displayName:
      "Proportion of Sick children 2 months- 5yrs malaria cases that received ACT seen by VHTs in the community",
    function: "ratio",
    numerator: { dataElementId: "CBy1S08hyCf", function: "nansum" },
    denominator: { dataElementId: "UvBZpWxJ8ff", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2240",
    displayName:
      "Proportion of Sick children 2 months -5yrs with fever + danger sign seen in the community",
    function: "ratio",
    numerator: { dataElementId: "faPanhYeBEK", function: "nansum" },
    denominator: { dataElementId: "ZPgTzBpXQtT", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2241",
    displayName:
      "Proportion of Sick children 2 months -  5yrs with fever and danger sign treated with rectal artesunate by VHTs",
    function: "ratio",
    numerator: { dataElementId: "iA5HPQs1eYm", function: "nansum" },
    denominator: { dataElementId: "faPanhYeBEK", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2242",
    displayName:
      "Proportion  of Sick children 2 months - 5 years seen by VHT and treated within 24hrs for fever in the community",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: "ZPgTzBpXQtT", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2243",
    displayName:
      "Proportion of Sick children who were managed by VHT who recovered",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: "lA61RMKevuI", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2244",
    displayName:
      "Proportion  of sick Children 2 months - 5 years with fast breathing / Pneumonia",
    function: "ratio",
    numerator: { dataElementId: "um49t84MUlL", function: "nansum" },
    denominator: { dataElementId: "lA61RMKevuI", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2245",
    displayName:
      "Proportion of Sick children 2 months - 5yrs confirmed pneumonia  that received amoxicillin dispersible tablets",
    function: "ratio",
    numerator: { dataElementId: "bbO4WjlQOYb", function: "nansum" },
    denominator: { dataElementId: "um49t84MUlL", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2246",
    displayName:
      "Proportion of Sick children 2months - 5yrs seen by VHT and treated within 24hrs for pneumonia",
    function: "ratio",
    numerator: { dataElementId: "zgTA9Ie3juu", function: "nansum" },
    denominator: { dataElementId: "um49t84MUlL", function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2247",
    displayName:
      "Proportion of sick children under 5 years referred to the Health Unit",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "ICCM",
  },
  {
    key: "2248",
    displayName: "Proportion of villages with stock out of the ACT",
    function: "ratio",
    numerator: { dataElementId: "NSxGAut6ETN", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "Drug Availability",
  },
  {
    key: "2249",
    displayName: "Proportion of villages with stock out of RDTs",
    function: "ratio",
    numerator: { dataElementId: "xCPny2fq8Wj", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "Drug Availability",
  },
  {
    key: "2250",
    displayName: "Proportion of villages with stock out of rectal Artesunate ",
    function: "ratio",
    numerator: { dataElementId: "iA5HPQs1eYm", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "Drug Availability",
  },
  {
    key: "2251",
    displayName: "Proportion of villages with stock out of Amoxycillin",
    function: "ratio",
    numerator: { dataElementId: "crKmead9CLB", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "Drug Availability",
  },
  {
    key: "2252",
    displayName: "Proportion of villages with stock out of ORS+ Zinc",
    function: "ratio",
    numerator: { dataElementId: "NaQbTMBxlbg", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "Drug Availability",
  },
  {
    key: "2253",
    displayName: "Proportion of villages with stock out of Misoprostol",
    function: "ratio",
    numerator: { dataElementId: "DltEqWQ2OPq", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "Drug Availability",
  },
  {
    key: "2254",
    displayName: "Proportion of villages with stock out of Injectable DMPA",
    function: "ratio",
    numerator: { dataElementId: "ONWYhq9LETF", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "FP",
  },
  {
    key: "2255",
    displayName:
      "Proportion of villages with stock out of combined Oral Contraceptive",
    function: "ratio",
    numerator: { dataElementId: "hKb86qZzZQL", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "FP",
  },
  {
    key: "2256",
    displayName: "Proportion of villages with stock out of condoms",
    function: "ratio",
    numerator: { dataElementId: "FOPA1BKQx6b", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "FP",
  },
  {
    key: "2257",
    displayName:
      "Proportion of villages with stock out of Progestin Only pills",
    function: "ratio",
    numerator: { dataElementId: "WGl14TNwoPO", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "FP",
  },
  {
    key: "2258",
    displayName:
      "Proportion of villages with stock out of emergency contraceptives",
    function: "ratio",
    numerator: { dataElementId: "PIqQMpkfOEx", function: "nansum" },
    denominator: { dataElementId: "xCP0SCOn2ov", function: "nansum" },
    group: "FP",
  },
  {
    key: "2259",
    displayName:
      "Number of assistive devices/technologies (AT) provided  by category to Persons with Disabilities",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "Disability and Rehabilitation",
  },
  {
    key: "2260",
    displayName:
      "Proportion of districts/health facilities reached with messages on disability prevention and essential rehabilitation care services.",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "Disability and Rehabilitation",
  },
  {
    key: "2261",
    displayName:
      "Proportion of endemic districts/communities that have  blindness (trachoma and onchocerciasis) prevention and control activities. ",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "Disability and Rehabilitation",
  },
  {
    key: "2262",
    displayName:
      "Proportion of districts health facilities/workplaces with and implementing occupational health and safety (OHS) plans.",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "Disability and Rehabilitation",
  },
  {
    key: "2263",
    displayName:
      "Proportion of health facilities workers who have been oriented trained on provision of services for health of older persons",
    function: "ratio",
    numerator: { dataElementId: null, function: "nansum" },
    denominator: { dataElementId: null, function: "nansum" },
    group: "Disability and Rehabilitation",
  },
  {
    key: "vitamin_a2__nutrition_female",
    displayName: "2nd doses of vitamin A to female U5",
    function: "nansum",
    numerator: { dataElementId: "A2ZOozUNmDz", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },
  {
    key: "vitamin_a2__nutrition_male",
    displayName: "2nd doses of vitamin A to male U5",
    function: "nansum",
    numerator: { dataElementId: "A2ZOozUNmDz", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },

  {
    key: "dpt1__u1_outreach",
    displayName: "DPT1 doses to U1 (outreach)",
    function: "nansum",
    numerator: { dataElementId: "Ys31ug5E3f1", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "dpt1__u1_static",
    displayName: "DPT1 doses to U1 (static)",
    function: "nansum",
    numerator: { dataElementId: "Ys31ug5E3f1", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "dpt3__u1_outreach",
    displayName: "DPT3 doses to U1 (outreach)",
    function: "nansum",
    numerator: { dataElementId: "ujs4ipzA4tb", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "dpt3__u1_static",
    displayName: "DPT3 doses to U1 (static)",
    function: "nansum",
    numerator: { dataElementId: "ujs4ipzA4tb", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "hpv2__community",
    displayName: "HPV2 doses to girls (community)",
    function: "nansum",
    numerator: { dataElementId: "zcT0YplhdAB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "hpv2__school",
    displayName: "HPV2 doses to girls (school)",
    function: "nansum",
    numerator: { dataElementId: "zcT0YplhdAB", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "contraceptives_male_condom__fp_contraception_u20",
    displayName: "Men using male condoms (under 20)",
    function: "nansum",
    numerator: { dataElementId: "bkCFVYMFMed", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "mr1__u1_outreach",
    displayName: "MR1 doses to U1 (outreach)",
    function: "nansum",
    numerator: { dataElementId: "WAjgHQVxVVm", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "mr1__u1_static",
    displayName: "MR1 doses to U1 (static)",
    function: "nansum",
    numerator: { dataElementId: "WAjgHQVxVVm", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "pcv1__u1_outreach",
    displayName: "PCV1 doses to U1 (outreach)",
    function: "nansum",
    numerator: { dataElementId: "NbG01i1Md55", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "pcv1__u1_static",
    displayName: "PCV1 doses to U1 (static)",
    function: "nansum",
    numerator: { dataElementId: "NbG01i1Md55", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "pcv3__u1_outreach",
    displayName: "PCV3 doses to U1 (outreach)",
    function: "nansum",
    numerator: { dataElementId: "QHawVF72X6E", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "pcv3__u1_static",
    displayName: "PCV3 doses to U1 (static)",
    function: "nansum",
    numerator: { dataElementId: "QHawVF72X6E", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "sti_other__fp_stds_female",
    displayName: "STI cases not related to SGBV (female)",
    function: "nansum",
    numerator: { dataElementId: "KaqDbaq0Yce", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "sti_other__fp_stds_male",
    displayName: "STI cases not related to SGBV (male)",
    function: "nansum",
    numerator: { dataElementId: "KaqDbaq0Yce", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "sti_gbv__fp_stds_female",
    displayName: "STI cases related to SGBV (female)",
    function: "nansum",
    numerator: { dataElementId: "Cw3RNymXWjr", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "sti_gbv__fp_stds_male",
    displayName: "STI cases related to SGBV (male)",
    function: "nansum",
    numerator: { dataElementId: "Cw3RNymXWjr", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "tb_cases_registered__tb_female_a5",
    displayName: "TB cases registered in treatment unit (females over five)",
    function: "nansum",
    numerator: { dataElementId: "vSaFiVhebVQ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "tb_cases_registered__tb_female_u5",
    displayName: "TB cases registered in treatment unit (females under five)",
    function: "nansum",
    numerator: { dataElementId: "vSaFiVhebVQ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "tb_cases_registered__tb_male_a5",
    displayName: "TB cases registered in treatment unit (males over five)",
    function: "nansum",
    numerator: { dataElementId: "vSaFiVhebVQ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "tb_cases_registered__tb_male_u5",
    displayName: "TB cases registered in treatment unit (males under five)",
    function: "nansum",
    numerator: { dataElementId: "vSaFiVhebVQ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "TB",
  },
  {
    key: "td1__pregnant",
    displayName: "TD1 doses (pregnant)",
    function: "single",
    numerator: { dataElementId: "oj4ttY118Fg", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "td2__nonpregnant",
    displayName: "TD2 doses (nonpregnant)",
    function: "nansum",
    numerator: { dataElementId: "OrKSwpDxQaJ", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "EPI",
  },
  {
    key: "contraceptives_female_condom__fp_contraception_u20",
    displayName: "Women using female condoms (under 20)",
    function: "nansum",
    numerator: { dataElementId: "Onpo1O1A7jr", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "contraceptives_oral_lofemenal__fp_contraception_u20",
    displayName: "Women using oral lo-femenal contraceptives (under 20)",
    function: "nansum",
    numerator: { dataElementId: "dt0srLW7MmK", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "contraceptives_oral_ovrette__fp_contraception_u20",
    displayName: "Women using oral ovrette contraceptives (under 20)",
    function: "nansum",
    numerator: { dataElementId: "dyfJZ2Llr6F", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "contraceptives_oral_other__fp_contraception_u20",
    displayName: "Women using other oral contraceptives (under 20)",
    function: "nansum",
    numerator: { dataElementId: "NXCJqj7Edfo", function: "single" },
    denominator: { dataElementId: 1, function: "single" },
    group: "FP",
  },
  {
    key: "11109",
    displayName: "1st & 2nd doses of vitamin A to female U5",
    function: "nansum",
    numerator: {
      dataElementId: ["vI52cxgsBNv", "A2ZOozUNmDz"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },

  {
    key: "11110",
    displayName: "1st & 2nd doses of vitamin A to male U5",
    function: "nansum",
    numerator: {
      dataElementId: ["vI52cxgsBNv", "A2ZOozUNmDz"],
      function: "nansum",
    },
    denominator: { dataElementId: 1, function: "single" },
    group: "NUT",
  },
];

export default indicatorMeta;
