const overviewIndicatorMeta = [
  {
    key: "OPD attendance",
    displayName: "OPD attendance",
    function: "nansum",
    numerator: {
      dataElementId: ["sv6SeKroHPV", "sQ4EexvvhVe"],
      function: "nansum",
    },
    denominator: { dataElementId: "1", function: "single" },
    group: "GENERAL",
    reportingFrequency: "monthly",
    // meta: {},
  },
  {
    key: "1st ANC Visits",
    displayName: "1st ANC Visits",
    function: "single",
    numerator: { dataElementId: "Q9nSogNmKPt", function: "single" },
    denominator: { dataElementId: "1", function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
    // meta: {},
  },
  {
    key: "Deliveries in unit",
    displayName: "Deliveries in unit",
    function: "single",
    numerator: { dataElementId: "idXOxt69W0e", function: "single" },
    denominator: { dataElementId: "1", function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
    // meta: {},
  },
  {
    key: "Newborn deaths",
    displayName: "Newborn deaths",
    function: "single",
    numerator: { dataElementId: "hrTskGHP0Av", function: "single" },
    denominator: { dataElementId: "1", function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
    // meta: {},
  },
  {
    key: "Maternal deaths",
    displayName: "Maternal deaths",
    function: "single",
    numerator: { dataElementId: "F8Iz6QcexWB", function: "single" },
    denominator: { dataElementId: "1", function: "single" },
    group: "MNCH",
    reportingFrequency: "monthly",
    // meta: {},
  },
  {
    key: "DPT3 doses to U1",
    displayName: "DPT3 doses to U1",
    function: "single",
    numerator: { dataElementId: "Ys31ug5E3f1", function: "single" },
    denominator: { dataElementId: "1", function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
    // meta: {},
  },
  {
    key: "MR1 doses to U1",
    displayName: "MR1 doses to U1",
    function: "single",
    numerator: { dataElementId: "WAjgHQVxVVm", function: "single" },
    denominator: { dataElementId: "1", function: "single" },
    group: "EPI",
    reportingFrequency: "monthly",
    // meta: {},
  },
  {
    key: "SAM cases identified",
    displayName: "SAM cases identified",
    function: "nansum",
    numerator: {
      dataElementId: ["dgnUFBzt87d", "LX6uCvQ7a7W", "zvJyAAeman2"],
      function: "nansum",
    },
    denominator: { dataElementId: "1", function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
    // meta: {},
  },
  {
    key: "1st & 2nd doses of vitamin A to U5",
    displayName: "1st & 2nd doses of vitamin A to U5",
    function: "nansum",
    numerator: {
      dataElementId: ["vI52cxgsBNv", "A2ZOozUNmDz"],
      function: "nansum",
    },
    denominator: { dataElementId: "1", function: "single" },
    group: "NUT",
    reportingFrequency: "monthly",
    // meta: {},
  },
  {
    key: "TB cases registered in treatment unit",
    displayName: "TB cases registered in treatment unit",
    function: "single",
    numerator: { dataElementId: "vSaFiVhebVQ", function: "single" },
    denominator: { dataElementId: "1", function: "single" },
    group: "TB",
    // meta: {},
  },
  {
    key: "Injuries related to SGBV",
    displayName: "Injuries related to SGBV",
    function: "single",
    numerator: { dataElementId: "bRYoCXTmJCB", function: "single" },
    denominator: { dataElementId: "1", function: "single" },
    group: "FP",
    reportingFrequency: "monthly",
    // meta: {},
  },
];

export default overviewIndicatorMeta;
